### ISSUE TITLE
Unable to unlock or lock

### ISSUE THREAD

**Issue by barracksbuilder** [dknowles2/ha-schlage#88]
I am not able to lock or unlock the encode plus door handle. The status is working correctly. When I issue a lock or unlock command it's giving me a gateway timeout. If I manually punch in the address api.allegion.yonomi.cloud I can reach it and returns a 401 unauthorized. Not sure what to do here.

```
2023-06-22 10:18:32.640 DEBUG (MainThread) [custom_components.schlage] Finished fetching schlage data in 1.393 seconds (success: True)
2023-06-22 10:18:48.459 DEBUG (MainThread) [custom_components.schlage] Finished fetching schlage data in 1.211 seconds (success: True)
2023-06-22 10:19:04.421 DEBUG (MainThread) [custom_components.schlage] Finished fetching schlage data in 1.174 seconds (success: True)
2023-06-22 10:19:20.273 DEBUG (MainThread) [custom_components.schlage] Finished fetching schlage data in 1.026 seconds (success: True)
2023-06-22 10:19:22.582 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall lock.unlock (c:01H3HTZQYSN0GZHMWD2NK6VWB3): entity_id=['lock.kitchen_door_lock']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyschlage/auth.py", line 60, in wrapper
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: https://api.allegion.yonomi.cloud/v1/devices/3da2f435-09f6-5c68-a3a9-ac400b81b77e/commands

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1928, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 111, in _async_unlock
    await entity.async_unlock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/schlage/lock.py", line 110, in async_unlock
    await self.hass.async_add_executor_job(self._lock.unlock)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyschlage/lock.py", line 134, in unlock
    self._toggle(0)
  File "/usr/local/lib/python3.11/site-packages/pyschlage/lock.py", line 116, in _toggle
    self._send_command("changelockstate", data)
  File "/usr/local/lib/python3.11/site-packages/pyschlage/lock.py", line 101, in _send_command
    self._auth.request("post", path, json=json)
  File "/usr/local/lib/python3.11/site-packages/pyschlage/auth.py", line 70, in wrapper
    raise UnknownError(message) from ex
pyschlage.exceptions.UnknownError: Gateway Timeout
```

**Comment by erpeters3** [comment]
Same exact issue.  No control but status is right.

**Comment by dknowles2** [comment]
Did you set up your lock with HomeKit? My understanding is that the Encode Plus locks don't work if you do that, as it changes something about how the API behaves.

**Comment by barracksbuilder** [comment]
Sorry I mistyped, it is not an encode plus it is an Encode WiFi Accent Lever Smart Lock. It seems to be something with the library as it's not able to connect. I ended up using mcnutter1's code and it is able to display the status and lock/unlock successfully. I do not use homekit, it is connected to wifi.

**Comment by Dproctor95** [comment]
I also have an encode lever lock and am unable to lock or unlock with HA.  It will update the correct status when I unlock or lock with the Schlage Home app and my 2 Encode deadbolt locks both work fine when using HA to lock or unlock.
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/schlage/lock.py:110 
Integration: Schlage Locks (documentation, issues) 
First occurred: 2:02:53 PM (2 occurrences) 
Last logged: 2:03:32 PM

Error executing service: <ServiceCall lock.unlock (c:01H4BZR6TS7TBG3Z14HFH75Y6R): entity_id=['lock.garage_entry_door_lock']>
Error executing service: <ServiceCall lock.unlock (c:01H4BZSCTAF1RGCS1S369ESH9S): entity_id=['lock.garage_entry_door_lock']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyschlage/auth.py", line 60, in wrapper
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: https://api.allegion.yonomi.cloud/v1/devices/fc5244ac-3c5c-5a48-8085-66d3125d887d/commands

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1928, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 111, in _async_unlock
    await entity.async_unlock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/schlage/lock.py", line 110, in async_unlock
    await self.hass.async_add_executor_job(self._lock.unlock)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyschlage/lock.py", line 134, in unlock
    self._toggle(0)
  File "/usr/local/lib/python3.11/site-packages/pyschlage/lock.py", line 116, in _toggle
    self._send_command("changelockstate", data)
  File "/usr/local/lib/python3.11/site-packages/pyschlage/lock.py", line 101, in _send_command
    self._auth.request("post", path, json=json)
  File "/usr/local/lib/python3.11/site-packages/pyschlage/auth.py", line 70, in wrapper
    raise UnknownError(message) from ex
pyschlage.exceptions.UnknownError: Gateway Timeout

**Comment by dknowles2** [comment]
Okay, I'm guessing that some locks use a different path to lock/unlock. mcnutter1's code handled this differently than mine. Let me take a closer look.

**Comment by Sy1v** [comment]
Hey Team, seems there was an update to the Schlage app. This resulted in the lock not working anymore via HA (for me at least). They added the ability to link a Ring account to Schlage. My guess is they changed some API to support it?

**Comment by ThePostman22** [comment]
Same issue with encode Wi-Fi lever lock in HA tied to HomeKit. Let me know if I can provide any information that could help.

**Comment by dknowles2** [comment]
> Hey Team, seems there was an update to the Schlage app. This resulted in the lock not working anymore via HA (for me at least). They added the ability to link a Ring account to Schlage. My guess is they changed some API to support it?

What lock model?

**Comment by dknowles2** [comment]
> Same issue with encode Wi-Fi lever lock in HA tied to HomeKit. Let me know if I can provide any information that could help.

I'm pretty sure once you tie your lock to HomeKit the Schlage API stops working. If you want the integration to work, you'll need to unpair with HomeKit and make sure you have a Schlage account.

**Comment by ThePostman22** [comment]
> > Same issue with encode Wi-Fi lever lock in HA tied to HomeKit. Let me know if I can provide any information that could help.
> 
> I'm pretty sure once you tie your lock to HomeKit the Schlage API stops working. If you want the integration to work, you'll need to unpair with HomeKit and make sure you have a Schlage account.

So I have the lock setup and working in the Schlage app. It won’t natively connect to HomeKit so I am trying to use your plugin to bring it into HomeKit using HA. I get status updates through HomeKit but I am unable to lock or unlock the device from HomeKit.

**Comment by dknowles2** [comment]
> So I have the lock setup and working in the Schlage app. It won’t natively connect to HomeKit so I am trying to use your plugin to bring it into HomeKit using HA. I get status updates through HomeKit but I am unable to lock or unlock the device from HomeKit.

I just exported my lock from HA to HomeKit and it seems to lock & unlock through HomeKit just fine. Does it not work via HA either?

**Comment by ThePostman22** [comment]
> > So I have the lock setup and working in the Schlage app. It won’t natively connect to HomeKit so I am trying to use your plugin to bring it into HomeKit using HA. I get status updates through HomeKit but I am unable to lock or unlock the device from HomeKit.
> 
> I just exported my lock from HA to HomeKit and it seems to lock & unlock through HomeKit just fine. Does it not work via HA either?

ah so good call! I just checked and it's not allowing me to lock/unlock in HA either, the following error pops up on the bottom left.

<img width="377" alt="Screenshot 2023-07-26 at 21 33 25" src="https://github.com/dknowles2/ha-schlage/assets/64911813/44ad4fef-1177-47b2-ae59-3388bb6ac358">

I found this in the logs:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: lsiopy/lib/python3.11/site-packages/pyschlage/auth.py:70
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:32:56 PM (7 occurrences)
Last logged: 9:33:44 PM

[140098550260880] Gateway Timeout
Traceback (most recent call last):
  File "/config/lsiopy/lib/python3.11/site-packages/pyschlage/auth.py", line 60, in wrapper
    resp.raise_for_status()
  File "/lsiopy/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: https://api.allegion.yonomi.cloud/v1/devices/a142d286-a625-5c24-bc50-3ad1f1568931/commands

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/lock/__init__.py", line 111, in _async_unlock
    await entity.async_unlock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/schlage/lock.py", line 110, in async_unlock
    await self.hass.async_add_executor_job(self._lock.unlock)
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/lsiopy/lib/python3.11/site-packages/pyschlage/lock.py", line 134, in unlock
    self._toggle(0)
  File "/config/lsiopy/lib/python3.11/site-packages/pyschlage/lock.py", line 116, in _toggle
    self._send_command("changelockstate", data)
  File "/config/lsiopy/lib/python3.11/site-packages/pyschlage/lock.py", line 101, in _send_command
    self._auth.request("post", path, json=json)
  File "/config/lsiopy/lib/python3.11/site-packages/pyschlage/auth.py", line 70, in wrapper
    raise UnknownError(message) from ex
pyschlage.exceptions.UnknownError: Gateway Timeout
```

**Comment by dknowles2** [comment]
What's your lock's model number? It should be in the "Device Info" section in HA.

![image](https://github.com/dknowles2/ha-schlage/assets/150213/49cbc292-1254-4e2e-a9e1-8891ca5e7d6c)

**Comment by ThePostman22** [comment]
> What's your lock's model number? It should be in the "Device Info" section in HA.
> 
> ![image](https://user-images.githubusercontent.com/150213/256408329-49cbc292-1254-4e2e-a9e1-8891ca5e7d6c.png)

See below.

<img width="364" alt="Screenshot 2023-07-26 at 22 42 48" src="https://github.com/dknowles2/ha-schlage/assets/64911813/54e28393-a02c-4122-9037-e238ada92e0d">

**Comment by dknowles2** [comment]
Okay, I think https://github.com/dknowles2/pyschlage/pull/76 will fix it. I'll get a new integration build pushed shortly with that fix.

**Comment by dknowles2** [comment]
Okay, new version published. Give that a try and see if it fixes things. If not I'll try and take another look later this week.

**Comment by ThePostman22** [comment]
About to go to bed but I just updated and was able to unlock/lock (with very little latency I might add!) from both HA and homekit!

Thank you so much! If I notice any other odd behavior I will circle back.
